apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tron
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/brandonholcombe/tron.git
    targetRevision: HEAD
    path: K8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tron
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
